### ISSUE TITLE
Using IPv4

### ISSUE THREAD

**Issue by ghost** [birros/web-archives#10]
Hey, sorry to bother you again. Thing is, Parrot has this proxy called anonsurf, that diverts all internet traffic trough tor. Whenever I use it, Web Archives fails to launch.

```
** (web-archives:3): ERROR **: 12:54:22.330: server.vala:26: Could not listen on address ::1, port 41509: Error binding to address: Cannot assign requested address
```

Asking around, I was told this message indicates web-archives is trying to access its localserver using IPv6, but anonsurf uses IPv4 only.

> anonsurf is only ipv4

> Your web-archives is trying to build on something that doesnt exist while anonsurf is running

>Use ipv4 local host and itll work

I like being able to make searches without even accessing the internet. Beats having to anonimize my access to it. Though I wouldn't like to have to chose between the two. Is there a way I could change web-archive's connection options or have it try both IPv6 and 4 before failing?

Thanks.

**Comment by birros** [comment]
@hThoreau The fixed version of the web-achives will be published in about 3 hours. Can you try it and confirm in comment that the patch works?

Thanks

**Comment by ghost** [comment]
It does, thank you so much for your great work!
