### ISSUE TITLE
Not being able to download updated versions of zim files

### ISSUE THREAD

**Issue by ghost** [birros/web-archives#13]
Hello there, I've tried to download updated versions of zim files I currently have, but this happened:

- If I tried to download the version of Wikipedia from 2019-05-11 with no videos with the "Peer-to-Peer network" option, nothing happens. This shows up in the terminal:

```
** INFO: 18:03:57.804: file-downloader.vala:33: header_size : 0
** INFO: 18:03:57.804: file-downloader.vala:34: header_modified : 0
** INFO: 18:03:57.804: file-downloader.vala:37: local_modified : 0
```
- Otherwise, if I chose the "From a server" option, this 404 page opens: https://download.kiwix.org/zim/wikipedia/wikipedia_en_simple_all_novid_2019-05.zim

**Comment by birros** [comment]
@hThoreau This is due to the fact that this zim file no longer exists, you must refresh the zim list before downloading one.

**Comment by ghost** [comment]
Hello there,

Sorry for the late response. I've done what you suggested and a new list of files appeared. Strangely, though, all of them seem to be only text based versions of the pages. Is this the expected behaviour?

![image](https://user-images.githubusercontent.com/24997547/78391467-cead8080-75bc-11ea-9422-788db9e44f01.png)

**Comment by birros** [comment]
Ok, so your problem is solved, but you just highlighted a new problem, it comes from a format change in the tags.

So I am creating a new issue for this problem.
