### ISSUE TITLE
Language Issue

### ISSUE THREAD

**Issue by ghost** [birros/web-archives#15]
Hey, The language doesn't full update in to dutch language.

Here is a image with updated language
https://i.postimg.cc/kGXFYLMX/update-text.png

And here is image without updated language
https://i.postimg.cc/ncr6whL7/not-update.png

**Comment by birros** [comment]
Couple of things:

1. **You have to wait a few hours for the update to be downloadable**, so test it again in a few hours.

2. **I cannot test WebArchives in languages other than Spanish or French**. The error tickets I find are apparently fixed, except that the procedure for testing software using another language seems to work for everyone but me. The management of locales under flatpak is really chaotic.

So I forfeit, managing locales under Linux is really a torture. Sorry :disappointed:

I really hope that the Dutch support will be well deployed :crossed_fingers:

**Comment by ghost** [comment]
Sorry for the late but it still doesn't work, could you try to see if the france languse works.

**Comment by birros** [comment]
After some search, I finally discovered how to manage the locales under flatpak. So I tested the support of English, French, Spanish and Dutch. They all work :tada: 

Make sure you have Dutch support in your flatpak conf:
```shell
$ flatpak --system config --get languages
nl;en
$ flatpak --user config --get languages
nl;en
```

If not, run the following commands, this will update the locales of all runtimes in your flatpak including WebArchives:

```shell
$ flatpak --system config --set languages "nl;en"
$ flatpak --user config --set languages "nl;en"
$ flatpak update -y
```

Test WebArchives in Dutch with this:
```shell
$ LC_ALL=nl_NL flatpak run com.github.birros.WebArchives
```

I close this issue, I think it solves your problem :smiley:
