### ISSUE TITLE
Couple Questions

### ISSUE THREAD

**Issue by ghost** [birros/web-archives#18]
Is there something in the code that i did wrong? since it still doesn't display in dutch language.

#: src/app/ui/content/home-view.vala:19
msgid ""
"No archive automaticly detected on your system. <b>Please download one from "
"the following section.</b>"
msgstr "Geen archief automatisch gedetecteerd op uw systeem. <b>Download er één van "
"de volgende sectie.</b> "

And second is there a way for me to test the code first?

**Comment by birros** [comment]
Ths display problem comes from the `fuzzy` instruction which is automatically added by translation tools. I don't know why, all I know is that it should be removed.

**Comment by birros** [comment]
About tests, I advise you to have a look at **flatpak-builder**, I can't advise you anything on this subject knowing that on my machine the version of flatpak is a bit buggy, waiting for a patch in the weeks / months.

This bug: [Build directory not initialized, use flatpak build-init #237](https://github.com/flatpak/flatpak-builder/issues/237)
