### ISSUE TITLE
Initial refreshing of archives does not work

### ISSUE THREAD

**Issue by baumkuchen42** [birros/web-archives#19]
- **What:** Clicking on refresh for the initial fetching of remote archives does not seem to do anything
- **Console output:** 

```sh
(web-archives:2): Gtk-WARNING **: 18:41:33.788: Locale not supported by C library.
	Using the fallback 'C' locale.

** (web-archives:2): WARNING **: 18:41:36.899: file-downloader.vala:97: Error while getting peer-to-peer dbus connection: Could not connect: No such file or directory
```

- **Version:** web-archives 0.3.1

I am also getting a warning about trackers not being installed (it is and WebArchives has the rights to access it)

![image](https://user-images.githubusercontent.com/38891851/115434230-c1375880-a208-11eb-95ae-47f0b953fd85.png)

![image](https://user-images.githubusercontent.com/38891851/115434305-d613ec00-a208-11eb-8e7c-5a29968d79f8.png)

**Comment by birros** [comment]
Hello, can you give me more information about your setup?

1. Are you using Flatpak?
2. Which distro do you use?
3. Do you use vpn?

Thx :)

**Comment by baumkuchen42** [comment]
Oh sorry, I thought there was just a flatpak version.

Yes, I am using it as a flatpak on Fedora 34. I don't use a VPN. 

I am in my university's network though which seems to cause the [same issues as a VPN causes with shortwave ](https://gitlab.gnome.org/World/Shortwave/-/issues/562)

**Comment by birros** [comment]
So I pushed a new version that fixes these bugs, the problem comes from the new fedora 34 technology stack, which is now supported with version `v0.4.0`.

I hope this will work for you too, thanks for your contribution :)

**Comment by baumkuchen42** [comment]
Yes, it works! Thank you very much!
