### ISSUE TITLE
Update libzim dependence

### ISSUE THREAD

**Issue by kelson42** [birros/web-archives#33]
Web-archives relies on a pretty old version of the libzim. It is not garantied that most recent ZIM files will be rendered properly. An update of the libzim us highly recommended.

**Comment by birros** [comment]
Done!

WebArchives is [now compatible with libzim >= 7](https://github.com/birros/web-archives/blob/v0.5.0/build-aux/flatpak/com.github.birros.WebArchives.yml#L65).

The upgrade was made easier thanks to your [doc to migrate from version 6 to 7](https://github.com/openzim/libzim/blob/7.0.0/docs/6to7.rst).
I also took the time to improve the quality of the [libzim-glib](https://github.com/birros/libzim-glib) repo to make future migrations easier.

---

Unfortunately I don't have the time to rewrite WebArchives from scratch to improve performance and keep up with [GNOME Human Interface Guidelines](https://developer.gnome.org/hig/), maybe in a few years… ^^

---

Thanks for asking for an update, I had missed the breaking changes from v6 to v7.

**Comment by kelson42** [comment]
@birros Bravo! Appriciate your feedback!
Ping @mgautierfr
