### ISSUE TITLE
Setting default Zoom value

### ISSUE THREAD

**Issue by edo0** [birros/web-archives#8]
I would like to set a default Zoom value for the dictionary display window (let's say 125%), so that I do not have to adjust it manually every time I start the software.
Is there a way to accomplish such a task?

**Comment by birros** [comment]
For now, the zoom is never saved. The ideal would be to save the last zoom chosen by archive but it would take a long time to implement it, and my schedule does not allow me to do so.

A short-term solution would be to save the last zoom used regardless of the archive, in this situation I can fix it in the short term and update WebArchives later this week. @edo0 Would that be appropriate?

**Comment by edo0** [comment]
Thank you very much, that would be of great help indeed !!

**Comment by birros** [comment]
Done :)
